#!/bin/bash
# Unattended synthesis runner for Slack Daily Digest scheduled runs.
# Uses claude -p to synthesize the final markdown when run_digest.py outputs AGENT_HANDOFF.
# Generated by: python3 scripts/local_routine.py generate-runner [--output PATH]

set -euo pipefail

SKILL_DIR="${1:-}"
DATE="${2:-}"
SLOT="${3:-}"
SLACK_DIGEST_HOME="${SLACK_DIGEST_HOME:-$HOME/.slack-daily-digest}"

if [[ -z "$SKILL_DIR" || -z "$DATE" || -z "$SLOT" ]]; then
  echo "Usage: $0 <skill_dir> <date> <slot>" >&2
  exit 1
fi

export SLACK_DIGEST_HOME

SCRIPTS="$SKILL_DIR/scripts"
TEMPLATE="$SKILL_DIR/references/digest-template.md"
RUN_DIR="$SLACK_DIGEST_HOME/runs/$DATE"
SLOT_SAFE="${SLOT//:}"
DIGEST_JSON="$RUN_DIR/digest_${SLOT_SAFE}.json"
HISTORY_JSON="$RUN_DIR/history_${SLOT_SAFE}.json"
FINAL_MD="$RUN_DIR/final_${SLOT_SAFE}.md"

# Step 1: pull + build digest data.
# Exit 2 = AGENT_HANDOFF (expected control flow, not a fatal error).
# Use || to capture exit code without triggering set -e.
EXIT=0
python3 "$SCRIPTS/run_digest.py" --date "$DATE" --slot "$SLOT" || EXIT=$?

if [[ $EXIT -eq 0 ]]; then
  # Already published (final_*.md already existed and was valid)
  exit 0
fi

if [[ $EXIT -ne 2 ]]; then
  echo "run_digest.py failed unexpectedly with exit $EXIT" >&2
  exit $EXIT
fi

# Exit 2 = AGENT_HANDOFF: synthesize with claude -p
if [[ ! -f "$DIGEST_JSON" ]]; then
  echo "digest JSON missing: $DIGEST_JSON" >&2
  exit 1
fi

DIGEST=$(cat "$DIGEST_JSON")
TEMPLATE_CONTENT=$(cat "$TEMPLATE")

PROMPT="You are generating a Slack Daily Digest.

Date: $DATE
Slot: $SLOT

Follow the template exactly (v4 hard rules: never truncate messages, never use ellipsis).

=== DIGEST TEMPLATE ===
$TEMPLATE_CONTENT

=== DIGEST DATA (JSON) ===
$DIGEST

Write the full final markdown for the digest doc. Output ONLY the markdown, no preamble."

echo "$PROMPT" | claude --dangerously-skip-permissions -p --output-format text > "$FINAL_MD"

if [[ ! -s "$FINAL_MD" ]]; then
  echo "synthesis produced empty output" >&2
  exit 1
fi

# Verify final_*.md has real content (not just a filename or empty sections)
FINAL_SIZE=$(wc -c < "$FINAL_MD")
if [[ $FINAL_SIZE -lt 500 ]]; then
  echo "synthesis output suspiciously small (${FINAL_SIZE} bytes): $FINAL_MD" >&2
  exit 1
fi

# Step 2: publish the synthesized markdown to Lark
python3 "$SCRIPTS/run_digest.py" --publish-existing --date "$DATE" --slot "$SLOT"
