#!/usr/bin/env bash
# tools/build-registry.sh
# Rebuilds registry.yaml from skills/*/manifest.yaml and profiles/*.yaml.
# Run manually: bash tools/build-registry.sh
# Run in CI: automatically on every push to main.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

python3 - "$REPO_DIR" <<'PYEOF'
import sys, os, glob, yaml
from datetime import datetime, timezone

repo = sys.argv[1]
skills_dir = os.path.join(repo, "skills")
profiles_dir = os.path.join(repo, "profiles")
out_file = os.path.join(repo, "registry.yaml")
TEMPLATE = "_template"

skills = []
for manifest_path in sorted(glob.glob(os.path.join(skills_dir, "*/manifest.yaml"))):
    skill_name = os.path.basename(os.path.dirname(manifest_path))
    if skill_name == TEMPLATE:
        continue
    with open(manifest_path) as f:
        m = yaml.safe_load(f)
    skills.append({
        "name":                    m.get("name", skill_name),
        "version":                 m.get("version", "0.0.0"),
        "stage":                   m.get("stage", "experimental"),
        "description_for_install": (m.get("description_for_install") or "").strip(),
        "owners":                  m.get("owners", []),
        "path":                    f"skills/{skill_name}",
        "triggers":                m.get("triggers", []),
        "depends_on":              m.get("depends_on", {}),
    })

profiles = []
for profile_path in sorted(glob.glob(os.path.join(profiles_dir, "*.yaml"))):
    with open(profile_path) as f:
        p = yaml.safe_load(f)
    profiles.append({
        "name":        p.get("name", os.path.splitext(os.path.basename(profile_path))[0]),
        "description": (p.get("description") or "").strip(),
        "audience":    p.get("audience", ""),
        "includes":    p.get("includes", []),
    })

ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

# Build the YAML manually to keep formatting clean and readable
lines = [
    "# AUTO-GENERATED by tools/build-registry.sh on every push to main.",
    "# DO NOT HAND-EDIT — changes will be overwritten.",
    "#",
    "# Source of truth per skill: skills/<name>/manifest.yaml",
    "#",
    f"generated_at: {ts}",
    "",
    "skills:",
]

for s in skills:
    lines.append(f"  - name: {s['name']}")
    lines.append(f"    version: {s['version']}")
    lines.append(f"    stage: {s['stage']}")
    # description: block scalar, 6-space indent
    desc_lines = s['description_for_install'].splitlines()
    lines.append(f"    description_for_install: |")
    for dl in desc_lines:
        lines.append(f"      {dl.strip()}")
    lines.append(f"    owners: {s['owners']}")
    lines.append(f"    path: {s['path']}")
    if s['triggers']:
        lines.append(f"    triggers:")
        for t in s['triggers']:
            # quote if needed, keep unicode readable
            if any(c in t for c in ':#{}[]|>&*!,?'):
                lines.append(f"      - {yaml.dump(t, allow_unicode=True, default_flow_style=True).strip()}")
            else:
                lines.append(f"      - \"{t}\"")
    lines.append("")

lines.append("profiles:")
for p in profiles:
    lines.append(f"  - name: {p['name']}")
    lines.append(f"    audience: {p['audience']}")
    desc_lines = (p['description'] or "").splitlines()
    if any(dl.strip() for dl in desc_lines):
        lines.append(f"    description: |")
        for dl in desc_lines:
            lines.append(f"      {dl.strip()}")
    lines.append(f"    includes:")
    for item in p['includes']:
        if isinstance(item, dict):
            for skill, ver in item.items():
                lines.append(f"      - {skill}: \"{ver}\"")
        else:
            lines.append(f"      - {item}")
    lines.append("")

with open(out_file, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"registry.yaml rebuilt — {len(skills)} skill(s), {len(profiles)} profile(s)")
for s in skills:
    print(f"  {s['name']:<30} v{s['version']:<10} [{s['stage']}]")
PYEOF
